### Local minima and maxima, functions of 1 variable

#### Second derivative test

Let:

$ f(x) $ be some function

$ c = \{f'(x) = 0\} $ be a point of inflection

Then:

$ f''(c) > 0 $ then this point is a local minima

$ f''(c) < 0 $ then this point is a local maxima

#### Quadratic function of 1 variable

$ f(x) = 2x^2 - 20x + 10 $

$ f'(x) = 4x - 20 $

Where is its minima and maxima?

The point of inflection $ c $ is:

$ 4x - 20 = 0 $

$ 4x = 20 $

$ x = 5 $

$ f''(5) = 4 $, which is larger than 0, so this is a local minimum 

#### Cubic function of 1 variable

$ f(x) = 2x^3 -7x^2 -5x +4 $

$ f'(x) = 6x^2 - 14x - 5 $

You could use the quadratic formula to find the roots, but here they are:

In [12]:
format short
roots([6,-14,-5])

ans =

   2.64803
  -0.31470



$ f''(x) = 12x - 14 $

In [13]:
12 * 2.64803 - 14

12 * -0.31470 - 14

ans =  17.776
ans = -17.776


The point $ x = -0.31470 $ is a local maximum and the point $ x = 2.64803 $ is a local miminum.